# Generated by Django 4.2.4 on 2023-08-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingsandbox',
            name='scraped_on',
            field=models.DateField(auto_now=True),
        ),
    ]
