# Generated by Django 4.2.4 on 2023-08-10 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_scrapingsandbox_scraped_on'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scrapingsandbox',
            unique_together={('source_url', 'scraped_on')},
        ),
    ]
